export function getInitialData() {
  const now = Date.now();
  const ago = (m) => new Date(now - m * 60 * 1000).toISOString();
  return [
    {
      id: "n1",
      title: "Login Authentication Issues",
      body:
        "Zagreb Municipality opened a HIGH ticket. Users cannot log in; error 'Username or password incorrect'. @ana please check.",
      client: "Zagreb Municipality",
      domain: "Support",
      severity: "high",
      status: "Open",
      assignee: "Ana Marić",
      nextStep: "Escalate to auth service",
      dueAt: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
      ticketId: "TCK-5812",
      activityId: "ACT-904",
      attachments: [
        { name: "error-log.txt", type: "text" },
        { name: "screenshot.png", type: "image" },
      ],
      timeline: [
        { at: ago(120), text: "Created" },
        { at: ago(110), text: "Notified via Slack" },
        { at: ago(20), text: "Viewed by Ana" },
      ],
      createdAt: ago(15),
      unread: true,
      tags: ["ticket", "urgent"],
      channel: "in-app",
    },
    {
      id: "n2",
      title: "Proposal viewed",
      body: "Sports Club Dinamo viewed your contract proposal.",
      client: "Sports Club Dinamo",
      domain: "Sales",
      severity: "info",
      status: "Info",
      assignee: "Marko Petrović",
      nextStep: "Follow up email",
      dueAt: ago(-60),
      ticketId: null,
      activityId: "ACT-811",
      attachments: [],
      timeline: [
        { at: ago(70), text: "Email sent" },
        { at: ago(60), text: "Proposal viewed" },
      ],
      createdAt: ago(60),
      unread: true,
      tags: ["proposal"],
      channel: "email",
    },
    {
      id: "n3",
      title: "Demo tomorrow 9:00 AM",
      body: "Reminder for Split City Council demo.",
      client: "Split City Council",
      domain: "Sales",
      severity: "medium",
      status: "Scheduled",
      assignee: "Ana Marić",
      nextStep: "Join Zoom link",
      dueAt: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
      ticketId: null,
      activityId: "ACT-700",
      attachments: [],
      timeline: [{ at: ago(90), text: "Reminder created" }],
      createdAt: ago(90),
      unread: false,
      tags: ["calendar", "reminder"],
      channel: "in-app",
    },
    {
      id: "n4",
      title: "Report generation timeout",
      body: "Background report failed for Split City Council.",
      client: "Split City Council",
      domain: "System",
      severity: "medium",
      status: "Investigating",
      assignee: "Petra Babić",
      nextStep: "Retry job and capture metrics",
      dueAt: ago(-10),
      ticketId: "TCK-5890",
      activityId: null,
      attachments: [{ name: "stacktrace.txt", type: "text" }],
      timeline: [
        { at: ago(240), text: "Job started" },
        { at: ago(210), text: "Timeout error" },
      ],
      createdAt: ago(210),
      unread: true,
      tags: ["reports"],
      channel: "slack",
    },
  ];
}

